### ISSUE TITLE
Replace UTB with my OCR

### ISSUE THREAD

**Issue by hentaitaku** [x-cord/conan#2]
Hi i think its best when you replace the UTB subs that have many errors and are bad with my OCR.

https://mega.nz/file/xAJxBQ5R#sJR8pPa215FTDP-OLlJl6QlLa-VMOBeOuSUTTOT0k4M

Have fixed timing for episode 284 is now in sync.
Have made for all UTB subs a replacment OCR made from this episodes https://nyaa.si/view/1104407

**Comment by po5** [comment]
Thanks. Haven't replaced them yet because I have to restyle and give special attention to the subs, although most of the process is automated through `restyle.py` and `style-fixup.py`.
Eventually would like episodes with UTB available to either be a hybrid of lines from UTB and fansubs, or complete retranslations.

A good place to help atm is tagging lines as thoughts/flashback/any other relevant style: https://gist.github.com/po5/fc1b89b0f2f90851dcdeb4509ce6da5e

**Comment by po5** [comment]
In the process of integrating your OCRs, applying a bunch of fixes. Should hopefully be done sometime tomorrow.
